/* Turns the raw achievement photos in public/assets/<folder>/ into web-sized
   WebP variants, mirroring scripts/optimize-images.mjs.

   Run with:  node scripts/optimize-achievements.mjs   (needs `npm i -D sharp`)

   Unlike the event script the originals already live under public/assets/, so
   the sources are read in place and the generated files land beside them in a
   flat, URL-safe folder (public/assets/achievements/<slug>/). */
import sharp from 'sharp';
import fs from 'fs';
import path from 'path';

const WIDTHS = [640, 1024, 1600];
const OUT_ROOT = 'public/assets/achievements';

/* slug -> the raw files it is built from, in display order */
const GROUPS = [
  { slug: 'debate-club', sources: ['public/assets/Debate Club/P1.jpeg', 'public/assets/Debate Club/P2.jpeg'] },
];

const blur = {};

for (const group of GROUPS) {
  const out = path.join(OUT_ROOT, group.slug);
  fs.mkdirSync(out, { recursive: true });

  for (let i = 0; i < group.sources.length; i++) {
    const src = group.sources[i];
    const n = String(i + 1);
    const meta = await sharp(src).metadata();

    for (const w of WIDTHS) {
      const file = path.join(out, `${n}-${w}.webp`);
      await sharp(src)
        .rotate() // honour EXIF orientation
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: 78, effort: 6 })
        .toFile(file);
      console.log(file, (fs.statSync(file).size / 1024).toFixed(0) + 'KB');
    }

    /* 20px inline preview so a slot is never empty while the real file streams */
    const lqip = await sharp(src).rotate().resize({ width: 20 }).webp({ quality: 30 }).toBuffer();
    blur[`${group.slug}-${n}`] = `data:image/webp;base64,${lqip.toString('base64')}`;
    console.log(`  lqip ${group.slug}-${n}: ${lqip.length}B  (source ${meta.width}x${meta.height})`);
  }
}

fs.writeFileSync(
  'src/data/achievementBlur.js',
  '/* Generated by scripts/optimize-achievements.mjs — do not edit by hand. */\n' +
    'export const ACHIEVEMENT_BLUR = ' +
    JSON.stringify(blur, null, 2) +
    ';\n'
);
console.log('\nwrote src/data/achievementBlur.js');
