/* Turns the raw photos in source-photos/<slug>/ into web-sized WebP variants,
   mirroring scripts/optimize-images.mjs.

   Run with:  node scripts/optimize-gallery.mjs   (needs `npm i -D sharp`)

   Like scripts/optimize-images.mjs, the originals stay in source-photos/ so
   they are never published — only the generated WebP files ship, a few percent
   of the bytes. Each group names the section it renders in, so an event and an
   achievement land under public/assets/events/ and .../achievements/. */
import sharp from 'sharp';
import fs from 'fs';
import path from 'path';

const WIDTHS = [640, 1024, 1600];


/* Each group: which section it belongs to, the folder slug, and the raw files
   it is built from in display order. */
const GROUPS = [
  {
    section: 'achievements',
    slug: 'debate-club',
    sources: ['source-photos/debate-club/P1.jpeg', 'source-photos/debate-club/P2.jpeg'],
  },
  {
    section: 'events',
    slug: 'bswc-winter-2026',
    sources: [
      'source-photos/bswc-winter-2026/P1.jpeg',
      'source-photos/bswc-winter-2026/P2.jpeg',
      'source-photos/bswc-winter-2026/P3.jpeg',
    ],
  },
  /* One seminar, two entries: the room photo carries the event, the framed
     certificate carries the achievement, so each is sized for its own slot. */
  {
    section: 'events',
    slug: 'shukhee-seminar-2026',
    sources: ['source-photos/shukhee-seminar-2026/group.jpeg'],
  },
  {
    section: 'achievements',
    slug: 'shukhee-seminar-2026',
    sources: ['source-photos/shukhee-seminar-2026/certificate.jpeg'],
  },
];

const blur = {};

for (const group of GROUPS) {
  const out = path.join('public/assets', group.section, group.slug);
  fs.mkdirSync(out, { recursive: true });

  for (let i = 0; i < group.sources.length; i++) {
    const src = group.sources[i];
    const n = String(i + 1);
    const meta = await sharp(src).metadata();

    for (const w of WIDTHS) {
      const file = path.join(out, `${n}-${w}.webp`);
      await sharp(src)
        .rotate() // honour EXIF orientation
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: 78, effort: 6 })
        .toFile(file);
      console.log(file, (fs.statSync(file).size / 1024).toFixed(0) + 'KB');
    }

    /* 20px inline preview so a slot is never empty while the real file streams */
    const lqip = await sharp(src).rotate().resize({ width: 20 }).webp({ quality: 30 }).toBuffer();
    /* keyed by section too: one slug can appear in both sections */
    blur[`${group.section}/${group.slug}-${n}`] = `data:image/webp;base64,${lqip.toString(
      'base64'
    )}`;
    console.log(`  lqip ${group.section}/${group.slug}-${n}: ${lqip.length}B  (source ${meta.width}x${meta.height})`);
  }
}

fs.writeFileSync(
  'src/data/galleryBlur.js',
  '/* Generated by scripts/optimize-gallery.mjs — do not edit by hand. */\n' +
    'export const GALLERY_BLUR = ' +
    JSON.stringify(blur, null, 2) +
    ';\n'
);
console.log('\nwrote src/data/galleryBlur.js');
