/* Turns the raw camera JPEGs in source-photos/ into web-sized WebP variants.
   Run with:  node scripts/optimize-images.mjs   (needs `npm i -D sharp`)

   The 6000x4000 originals stay out of public/ so they are never published —
   only the generated public/assets/gub/*.webp ship, roughly 1% of the bytes. */
import sharp from 'sharp';
import fs from 'fs';
import path from 'path';

const SRC = 'source-photos/gub-2026';
const OUT = 'public/assets/gub';
const WIDTHS = [640, 1024, 1600];
const names = ['1', '2', '3', '4', '5', '6'];

fs.mkdirSync(OUT, { recursive: true });
const blur = {};

for (const n of names) {
  const src = path.join(SRC, `${n}.JPG`);
  const meta = await sharp(src).metadata();

  for (const w of WIDTHS) {
    const out = path.join(OUT, `${n}-${w}.webp`);
    await sharp(src)
      .rotate() // honour EXIF orientation
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: 78, effort: 6 })
      .toFile(out);
    console.log(out, (fs.statSync(out).size / 1024).toFixed(0) + 'KB');
  }

  /* 20px inline preview so a slot is never empty while the real file streams */
  const lqip = await sharp(src).rotate().resize({ width: 20 }).webp({ quality: 30 }).toBuffer();
  blur[n] = `data:image/webp;base64,${lqip.toString('base64')}`;
  console.log(`  lqip ${n}: ${lqip.length}B  (source ${meta.width}x${meta.height})`);
}

fs.writeFileSync(
  'src/data/gubBlur.js',
  '/* Generated by scripts/optimize-images.mjs — do not edit by hand. */\n' +
    'export const GUB_BLUR = ' +
    JSON.stringify(blur, null, 2) +
    ';\n'
);
console.log('\nwrote src/data/gubBlur.js');
